language: node_js
node_js:
  - '0.11'
  - '0.10'
deploy:
  provider: npm
  email: tcross@bandwidth.com
  on:
    repo: wtcross/grunt-lab
    branch: master
  api_key:
    secure: SOySFNPJa9ghqcDXA2tMjLlPnJm4JCmp1rEM5U4iiqY7qJoY6AfIzFSve01e1lLLqswAkUJAoI9/W8OWic9k5lNKfOVX8y/dxFzo+zvnz3oSp3lpfyAyR2rRpHcKmEPj3eLev+k1wbQmElD65HAhyfyOsPLneStO6zCjBYbDOzE=
